services:
  mongodb:
    image: mongodb/mongodb-enterprise-server:7.0.22-ubuntu2204
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
      - MONGODB_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGODB_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - ./software/mongo_crypt_shared_v1-linux-x86_64-enterprise-ubuntu2204-8.0.3/lib/mongo_crypt_v1.so:/usr/local/lib/mongo_crypt_v1.so
    networks:
      - mongo-net
  vault:
    image: hashicorp/vault:1.20
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=$VAULT_ADDR
      - VAULT_API_ADDR=$VAULT_API_ADDR
    #    command: server -config=/vault/config/vault-config.hcl
    command: server
    cap_add:
      - IPC_LOCK
    volumes:
      - ./app/vault/raft/config:/vault/config
      - ./app/vault/raft/data:/vault/data
    networks:
      - vault-network

networks:
  mongo-net:
  vault-network: