spring:
  application:
    name: mongodb-csfle
  data:
    mongodb:
      vault:
        uri: ${VAULT_URI}
      storage:
        uri: ${STORAGE_URI}
      database: ${MONGODB_DBNAME}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTHDB_NAME}
crypt:
  shared:
    lib:
      path: ${CRYPT_SHARED_LIB_PATH}

mongodb:
  key:
    vault:
      db: ${KEY_VAULT_DB}
      coll: ${KEY_VAULT_COLL}
  kms:
    provider: local
  master:
    key:
      file:
        path: ./master-key.txt
logging:
  level:
    root: INFO
    org:
      springframework:
        jdbc: INFO
    com:
      github:
        bruce_mig:
          mongodb_csfle: DEBUG
