spring:
  application:
    name: mongodb-csfle
  config:
    import: vault://
  data:
    mongodb:
      vault:
        uri: ${MONGO_VAULT_URI}
      storage:
        uri: ${STORAGE_URI}
      database: ${MONGODB_DBNAME}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTHDB_NAME}
  cloud:
    vault:
      host: ${VAULT_HOST}
      port: ${VAULT_PORT}
      scheme: http
      uri: ${HASHICORP_VAULT_URI}
      connection-timeout: 5000
      read-timeout: 15000
      token: ${VAULT_TOKEN}
      kv:
        backend: kv
        default-context: csfle
        enabled: true
      enabled: true
crypt:
  shared:
    lib:
      path: ${CRYPT_SHARED_LIB_PATH}

mongodb:
  key:
    vault:
      db: ${KEY_VAULT_DB}
      coll: ${KEY_VAULT_COLL}
  kms:
    provider: local
  master:
    key:
      file:
        path: ${FILE_MASTERKEY_PATH}
      vault:
        path: ${VAULT_MASTERKEY_PATH}
logging:
  level:
    root: INFO
    org:
      springframework:
        jdbc: INFO
        vault: DEBUG
    com:
      github:
        bruce_mig:
          mongodb_csfle: DEBUG
